/*
 * main.cpp
 *
 *  Created on: 18.7.2012
 *      Author: martint
 */


#include "ConverterOptions/optionsxmlparser.h"
#include "ConverterOptions/optionsdatabase.h"
/*
#include <iostream>

template<class T, class Allocator=std::allocator<T>  >

std::ostream& operator<<(std::ostream &os, const std::list<T>& t){
	typename std::list<T>::const_iterator it;
	for(it = t.begin(); it != t.end(); ++it){
		os << it->getName() <<" ";
	}
	return os;
}
*/
int main(){

	std::map<std::string, std::string> encodersWithDescription;
	encodersWithDescription["libx264"] = "description"; //generated by ffmpeg
	//encodersWithDescription["lsds"] = "tototot";
	ConverterOptions::OptionsXmlParser xmlParser("data/audio_video_settings.xml", encodersWithDescription);
/*
	ConverterOptions::Containers conts = xmlParser.loadContainers();
	std::cout<<conts.getContainers()<<std::endl;

	ConverterOptions::Container cont = conts.getContainerByName("mkv");

	std::cout<<cont.getFormats().getAudioFormatsList()<<std::endl;
	std::cout<<cont.getFormats().getVideoFormatsList()<<std::endl;

	ConverterOptions::Encoders encs = cont.getFormats().getFormatByName("H264").getEncoders();
	std::cout<<encs.getEncoders()<<std::endl;

	auto bitrs = encs.getEncoderByName("libx264").getBitrates();

	for(auto it = bitrs.begin(); it != bitrs.end(); ++it){
		std::cout<<it->getValue()<<std::endl;
	}
	*/
	ConverterOptions::OptionsDatabase optionsDatabase(&xmlParser);
	return 0;
}
